### ISSUE TITLE
Pihole 4.0

### ISSUE THREAD

**Issue by Berzerker** [janw/pi-hole-influx#1]
Pihole 4.0 seems to have an updated API, I get an error when trying to run the script "No JSON object could be decoded"

Path to API is correct and config is set in the ini

Any ideas?

**Comment by janw** [comment]
Hey @Berzerker 👋 I've been running v4.0 for a while now, too, and I cannot see anything changing in regards to the API. Could you post your config.ini with the login credentials removed?

**Comment by Berzerker** [comment]
`[influxdb]

port = PORT
hostname = InfluxDBIP
username = USERNAME
password = PASSWORD
database = DBNAME

[pihole]

api_location = http://127.0.0.1/admin/api.php
instance_name = pihole

# Time between reports to InfluxDB (in seconds)
reporting_interval = 10
`

The specific error I get is:

`Status: "Failed, to report to InfluxDB: No JSON object could be decoded"`

A more detailed error log if I run the python script manually:

`> ./piholeinflux.py                                                                                                                                                                       
Failed, to report to InfluxDB: No JSON object could be decoded
Traceback (most recent call last):
  File "./piholeinflux.py", line 58, in <module>
    send_msg(api.json())
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 888, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by janw** [comment]
Thanks for the input! One more thing I'd like you to try: what's coming up, when you're running `curl http://127.0.0.1/admin/api.php` from the terminal/ssh connection? It should be valid JSON; something like this:

```
{"domains_being_blocked":127487,"dns_queries_today":26384,"ads_blocked_today":
{"1253,"ads_percentage_today":4.74909,"unique_domains":11399,"queries_forwarde
{"d":14008,"queries_cached":11123,"clients_ever_seen":108,"unique_clients":25,
{""dns_queries_all_types":55334,"reply_NODATA":6170,"reply_NXDOMAIN":46,"reply
{"_CNAME":7073,"reply_IP":337475,"status":"enabled","gravity_last_updated":fil
{"e_exists":true,"absolute":1540697471,"relative":days":"4","hours":"10","minu
{"tes":"08"}}}
```

**Comment by Berzerker** [comment]
Cool, let me know if you find anything!

**Comment by Berzerker** [comment]
Hey! I figured it out. It looks like the API (most likely pihole) doesn't like the requests coming from localhost, so I set the IP in the config file to the actual LAN IP of the pihole box and it started working.

I imagine this is some limit on the API itself, but it's working now. Thanks again!
