### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by Troih** [janw/pi-hole-influx#12]
Hi,
Followed your instructions and trying to start the service but gets this error? 

I can go in to to python and write import request without any problems.
any thoughts?

```
Feb 22 00:26:41 raspberrypi systemd[1]: Starting Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization...
-- Subject: Unit piholeinflux.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit piholeinflux.service has begun starting up.
Feb 22 00:26:41 raspberrypi python3[2351]: Traceback (most recent call last):
Feb 22 00:26:41 raspberrypi python3[2351]:   File "/home/pi/pi-hole-influx/piholeinflux.py", line 5, in <module>
Feb 22 00:26:41 raspberrypi python3[2351]:     import requests
Feb 22 00:26:41 raspberrypi python3[2351]: ImportError: No module named 'requests'
Feb 22 00:26:42 raspberrypi systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 00:26:42 raspberrypi systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit piholeinflux.service has failed.
--
-- The result is failed.
Feb 22 00:26:42 raspberrypi systemd[1]: piholeinflux.service: Unit entered failed state.
Feb 22 00:26:42 raspberrypi systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Feb 22 00:26:42 raspberrypi sudo[2327]: pam_unix(sudo:session): session closed for user root
```

**Comment by janw** [comment]
When did you clone / last pull recent changes from the repo? There recently were breaking changes changing the default version from python2.7 to python3. 

Things to check:

1. Does executing `python3 -c 'import requests'` at the command line / shell yield any errors?
2. After pulling from the github repo, make sure the systemd service is up-to-date by running `sudo systemctl --system daemon-reload`, and restart the service again.

**Comment by Troih** [comment]
I removed everything and did your steps again but I get the same systemctl error when I try to start the service.
1. No errors. Works perfectly to import in the python3 prompt.

Im logged in as user pi and use sudo when needed.
 stange :/

**Comment by janw** [comment]
Cleaned up some things. Please open another ticket if the issue still exists.
