### ISSUE TITLE
Docker image does not work on PI 3b+

### ISSUE THREAD

**Issue by smishcraft** [janw/pi-hole-influx#22]
Hi,

I tried to use the docker image here in my PI 3B+ and i got this error  

`standard_init_linux.go:207: exec user process caused "exec format error"`

Is there a solution to this or do I have to do it the traditional way?

Kind Regards
Smish

**Comment by RonarPS** [comment]
Hi,

same error here. i think, the docker containter is nor arm ready - is there a chance to provide a arm-ready container?

Thanks  a lot

**Comment by janw** [comment]
Hey @smishcraft, @RonarPS! Thanks for giving me a reason to look into Docker on ARM / Raspberry Pi. 😁 I added a new tag for the image, `registry.gitlab.com/janw/pi-hole-influx:armv7`. Feel free to check it out and report back!
