### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by mash55** [janw/pi-hole-influx#29]
Can't get it to work. 
Pihole running on a PI 
Influxdb DB running on host SNIFFER (default port 8086) on same subnet than Pihole. DB 'PiholeStats' created in Influx.
Attached my user.tml file and the Errors.
Any input on what I am missing is very much appreciated
[Error.txt](https://github.com/janw/pi-hole-influx/files/3478624/Error.txt)
[user.toml.txt](https://github.com/janw/pi-hole-influx/files/3478625/user.toml.txt)

.

**Comment by janw** [comment]
Your `user.toml` does not contain a `instances = {}` entry.

**Comment by mash55** [comment]
thanks @janw... works now
