### ISSUE TITLE
 systemctl start piholeinflux.service errors

### ISSUE THREAD

**Issue by mrme02** [janw/pi-hole-influx#3]
Upon trying to run sudo systemctl start piholeinflux.service, I get the following error,

piholeinflux.service - Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization
   Loaded: loaded (/root/pi-hole-influx/piholeinflux.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-11-04 08:07:52 GMT; 5s ago
     Docs: https://github.com/janw/pi-hole-influx
  Process: 30168 ExecStart=/usr/bin/python /home/pi/pi-hole-influx/piholeinflux.py (code=exited, status=217/USER)
 Main PID: 30168 (code=exited, status=217/USER)
(determined with systemctl status piholeinflux.service )

I have given the proper path for the service, as I am logged in as root, ln -s /root/pi-hole-influx/piholeinflux.service /etc/systemd/system/

What else do I need to change or do better to get this to run, should I be doing this as root? What other paths should I change, and how?

**Comment by InfernoCV** [comment]
Inside the "piholeinflux.service" file is a line for "user" (line 8).  I just got this working last night and I had the exact same error code.  Needed to change the user account to the account that was going to be running the service.  So if you are running as root, try changing that line to be root instead of pi.

I also had to adjust line 11 (ExecStart) path to point to my home directory instead of the "pi" users home directory.  That should point to the location that you cloned the Git repo to locally on your pi-hole.

(I am running this on a Ubuntu 18.04 VM instead of a Pi.)

**Comment by NoBloodyABCorD** [comment]
On a fresh install of debian here with pihole running.  Grafana is running on another debian machine.  Fixing the two lines has resolved some of the issues with the service starting but still having errors.  My guess is I don't have the config set up correctly as I wasn't sure what IP address and user to provide.

```
● piholeinflux.service - Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization
   Loaded: loaded (/home/samgrund/pi-hole-influx/piholeinflux.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-01-28 16:49:26 EST; 7s ago
     Docs: https://github.com/janw/pi-hole-influx
  Process: 1171 ExecStart=/usr/bin/python /home/samgrund/pi-hole-influx/piholeinflux.py (code=exited, status=1/FAILURE)
 Main PID: 1171 (code=exited, status=1/FAILURE)
   Status: "Failed, to report to InfluxDB: HTTPConnectionPool(host='192.168.20.193', port=8086): Max retries exceeded with url: /write?db=pihole (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8aca1a149

Jan 28 16:49:26 pihole systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 16:49:26 pihole systemd[1]: piholeinflux.service: Unit entered failed state.
Jan 28 16:49:26 pihole systemd[1]: piholeinflux.service: Failed with result 'exit-code
```'

```
Jan 28 16:46:24 pihole python[1149]:   File "/home/localuser/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
Jan 28 16:46:24 pihole python[1149]:     resp = self.send(prep, **send_kwargs)
Jan 28 16:46:24 pihole python[1149]:   File "/home/localuser/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
Jan 28 16:46:24 pihole python[1149]:     r = adapter.send(request, **kwargs)
Jan 28 16:46:24 pihole python[1149]:   File "/home/localuser/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
Jan 28 16:46:24 pihole python[1149]:     raise ConnectionError(e, request=request)
Jan 28 16:46:24 pihole python[1149]: ConnectionError: HTTPConnectionPool(host='192.168.20.193', port=8086): Max retries exceeded with url: /write?db=pihole (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x
Jan 28 16:46:24 pihole systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 16:46:24 pihole systemd[1]: piholeinflux.service: Unit entered failed state.
Jan 28 16:46:24 pihole systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Jan 28 16:46:54 pihole systemd[1]: piholeinflux.service: Service hold-off time over, scheduling restart.
Jan 28 16:46:54 pihole systemd[1]: Stopped Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit piholeinflux.service has finished shutting down.
Jan 28 16:46:54 pihole systemd[1]: Starting Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization...
-- Subject: Unit piholeinflux.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit piholeinflux.service has begun starting up.
Jan 28 16:46:54 pihole systemd[1]: Started Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit piholeinflux.service has finished starting up.
--
-- The start-up result is done.
Jan 28 16:46:54 pihole python[1152]: Failed, to report to InfluxDB: HTTPConnectionPool(host='192.168.20.193', port=8086): Max retries exceeded with url: /write?db=pihole (Caused by NewConnectionError('<urllib3.connection.HTTPConnectio
Jan 28 16:46:54 pihole python[1152]: Traceback (most recent call last):
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/pi-hole-influx/piholeinflux.py", line 58, in <module>
Jan 28 16:46:54 pihole python[1152]:     send_msg(api.json())
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/pi-hole-influx/piholeinflux.py", line 51, in send_msg
Jan 28 16:46:54 pihole python[1152]:     INFLUXDB_CLIENT.write_points(json_body)
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/.local/lib/python2.7/site-packages/influxdb/client.py", line 490, in write_points
Jan 28 16:46:54 pihole python[1152]:     tags=tags, protocol=protocol)
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/.local/lib/python2.7/site-packages/influxdb/client.py", line 551, in _write_points
Jan 28 16:46:54 pihole python[1152]:     protocol=protocol
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/.local/lib/python2.7/site-packages/influxdb/client.py", line 327, in write
Jan 28 16:46:54 pihole python[1152]:     headers=headers
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/.local/lib/python2.7/site-packages/influxdb/client.py", line 267, in request
Jan 28 16:46:54 pihole python[1152]:     timeout=self._timeout
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
Jan 28 16:46:54 pihole python[1152]:     resp = self.send(prep, **send_kwargs)
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
Jan 28 16:46:54 pihole python[1152]:     r = adapter.send(request, **kwargs)
Jan 28 16:46:54 pihole python[1152]:   File "/home/localuser/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
Jan 28 16:46:54 pihole python[1152]:     raise ConnectionError(e, request=request)
Jan 28 16:46:54 pihole python[1152]: ConnectionError: HTTPConnectionPool(host='192.168.20.193', port=8086): Max retries exceeded with url: /write?db=pihole (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x
Jan 28 16:46:54 pihole systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 16:46:54 pihole systemd[1]: piholeinflux.service: Unit entered failed state.
Jan 28 16:46:54 pihole systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Jan 28 16:47:05 pihole sudo[663]: pam_unix(sudo:session): session closed for user root
Jan 28 16:47:11 pihole sudo[1155]: localuser : TTY=pts/0 ; PWD=/home/localuser ; USER=root ; COMMAND=/bin/journalctl -xe
Jan 28 16:47:11 pihole sudo[1155]: pam_unix(sudo:session): session opened for user root by localuser(uid=0)
```

**Comment by janw** [comment]
```
Jan 28 16:46:54 pihole python[1152]: ConnectionError: HTTPConnectionPool(host='192.168.20.193', port=8086): Max retries exceeded with url: /write?db=pihole …
```

This line tells me, that there's a problem with your influx db itself. Are you able to connect from other clients, and write data to it using this IP? Have you set up a user to access the influx?

**Comment by shanekorbel** [comment]
-- Unit piholeinflux.service has begun starting up.
Mar 06 13:24:38 HPC1 python3[6344]: Traceback (most recent call last):
Mar 06 13:24:38 HPC1 python3[6344]:   File "/root/pi-hole-influx/piholeinflux.py", line 6, in <module>
Mar 06 13:24:38 HPC1 python3[6344]:     from influxdb import InfluxDBClient
Mar 06 13:24:38 HPC1 python3[6344]: ModuleNotFoundError: No module named 'influxdb'
Mar 06 13:24:38 HPC1 systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 13:24:38 HPC1 systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Mar 06 13:24:38 HPC1 systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit piholeinflux.service has failed.
--
-- The result is RESULT.
Mar 06 13:24:49 HPC1 dockerd[1369]: time="2019-03-06T13:24:49.768247213-05:00" level=info msg="memberlist: Suspect cae67fb6deee has failed, no acks received"


 I've installed all the requirements and modified the home directory for my machine where everything resides on my host and I'm not able to figure out this error. 

Does the influxDB that you are connecting to _have_ to reside on the same machine running this service?

**Comment by rzae** [comment]
Hi,

I have the same error.
"Failed to enable unit: Unit file piholeinflux.service does not exist."

I Inside the "piholeinflux.service" , i add my user name and directory name.

I am on ubuntu server 18.04.

**Comment by janw** [comment]
Hey 👋  So I did some refactoring and cleanup today, so I'm hoping maybe theses issues are gone with the new version. Maybe give it a shot (maybe even the Docker image?) and please open a new issue if things are still not copasetic. Thanks!
