### ISSUE TITLE
weird counter behavior with dns_queries_today & ads_blocked_today

### ISSUE THREAD

**Issue by joeypiccola** [janw/pi-hole-influx#30]
I haven't paid much attention to Pi-hole's stats until I started graphing them with your script (which is awesome by the way). That said, now that I'm graphing them I'm not seeing the data represented in a way that aligns with your counter names. For example, I'd expect `dns_queries_today` to reset to `0` at midnight. However, not only does it not reset to `0` it seems to decrease slowly at a point during the day. I've only been running your `pi-hole-influx` for about 2.5 days, hopefully, the graphs below will help shed some light on the issue I've described. I also see similar behavior with `ads_blocked_today`. Thanks for the help \ taking a look. 

![q](https://user-images.githubusercontent.com/8612198/64214187-a619a880-ce6c-11e9-8b38-7701d9a1e26b.png)

The image below shows 4days. 
![q2](https://user-images.githubusercontent.com/8612198/64214242-e711bd00-ce6c-11e9-921c-a7f30d2b063a.png)

**Comment by junior466** [comment]
I too have noticed the same and can't make sense of it either.

Of course, I appreciate your time put into this script.

**Comment by joeypiccola** [comment]
Looking at the `:9090/admin/api.php` shows the counters. It's those that I believe are incorrect. Perhaps this is a question for https://github.com/pi-hole/pi-hole. Digging through their issues now.

**Comment by joeypiccola** [comment]
@junior466 well, looks like I’ve been here before and forgot. See my PiHole forum post from earlier this year. #facepalm. https://discourse.pi-hole.net/t/dashboard-total-queries-fluctuate-2k-every-30min/17639

**Comment by joeypiccola** [comment]
Forum post answers the behavior see with counters.
