### ISSUE TITLE
pi-hole-influx issue on startup

### ISSUE THREAD

**Issue by adznon** [janw/pi-hole-influx#33]
Hi Janw,

Am recieving the below error when trying to start pi-hole-influx. As you can see i have http in the setting so not sure what else is wrong.

Any ideas ?

Using config: {'INFLUX_HOST': '10.2.10.248', 'INFLUX_PORT': '8086', 'INFLUX_USERNAME': 'username', 'INFLUX_PASSWORD': 'Password', 'INFLUX_DATABASE': 'telegraf', 'PIHOLE_API': 'http://10.2.10.103/admin/api.php', 'PIHOLE_INSTANCE_NAME': 'Plexy_Secure=http://10.2.10.103/admin/api.php', 'REPORTING_INTERVAL': 500}

Failed, to report to InfluxDB: HTTPConnectionPool(host='10.2.10.103', port=80): Max retries exceeded with url: /admin/api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14ac93491a20>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

**Comment by kb5zuy** [comment]
This simply means that the pi-hole api is unreachable from the machine running the pi-hole-influx script.  does "curl http://10.2.10.103/admin/api.php" ?  Is the admin (web) interface enabled on the pi-hole?

**Comment by janw** [comment]
@adznon Are you still having this problem or was @kb5zuy's hint enough to fix it?

**Comment by adznon** [comment]
Yes, all fixed now. Thanks for checking
