### ISSUE TITLE
Status Code 1 / Failure

### ISSUE THREAD

**Issue by mihcox** [janw/pi-hole-influx#38]
After following the instructions, i get the following when running the app:

pi@raspberrypi:~/pi-hole-influx $ sudo systemctl status piholeinflux.service
● piholeinflux.service - Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization
   Loaded: loaded (/home/pi/pi-hole-influx/piholeinflux.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-12-30 10:56:00 CST; 15s ago
     Docs: https://github.com/janw/pi-hole-influx
  Process: 13205 ExecStart=/usr/bin/python3 /home/

**Comment by mihcox** [comment]
running the journal says:
pi@raspberrypi:~/pi-hole-influx $ journalctl -xe
Dec 30 10:59:39 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:39 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:40 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:40 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:40 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:40 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:40 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:40 raspberrypi dhcpcd[452]: eth0: received approval for 192.168.254.9
Dec 30 10:59:40 raspberrypi vncserver-x11[544]: AgentInitCheck: agent comms failure

**Comment by andrewgioia** [comment]
I'm also getting this error and can't figure out what the actual issue is. Is there any additional info on what could be causing this? Here's the message output:

```
$> systemctl status piholeinflux.service
● piholeinflux.service - Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization
   Loaded: loaded (/home/pi/pi-hole-influx/piholeinflux.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-04-15 09:42:14 EDT; 18s ago
     Docs: https://github.com/janw/pi-hole-influx
  Process: 10508 ExecStart=/usr/bin/python3 /home/pi/pi-hole-influx/piholeinflux.py (code=exited, status=1/FAILURE)
 Main PID: 10508 (code=exited, status=1/FAILURE)

$> journalctl -xe
-- An ExecStart= process belonging to unit piholeinflux.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 15 09:41:43 sylex systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit piholeinflux.service has entered the 'failed' state with result 'exit-code'.
Apr 15 09:41:43 sylex systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: A start job for unit piholeinflux.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit piholeinflux.service has finished with a failure.
--
-- The job identifier is 92054 and the job result is failed.
```

**Comment by janw** [comment]
Three years later, wow. 🤦  Sorry about the radio silence. If this issue still persists, feel free to re-open.
