### ISSUE TITLE
No ConfigParser

### ISSUE THREAD

**Issue by texasbobs** [janw/pi-hole-influx#4]
I am having a hard time getting this running. I'm on Mint instead of a rPi but I think I have most of it set up correctly. My problem is with the configparser. I can't seem to get it installed. I've tried configparser and ConfigParser with python and python3. Any help would be greatly appreciated.

bob@Mint:~/pi-hole-influx$ pip install ConfigParser
Collecting ConfigParser
Using cached https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
ImportError: No module named setuptools

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sNotAK/ConfigParser/

-- Unit piholeinflux.service has begun starting up.
Nov 18 13:11:00 Mint python[972]: Traceback (most recent call last):
Nov 18 13:11:00 Mint python[972]: File "/home/bob/pi-hole-influx/piholeinflux.py", line 7, in 
Nov 18 13:11:00 Mint python[972]: from configparser import configparser
Nov 18 13:11:00 Mint python[972]: ImportError: No module named configparser
Nov 18 13:11:00 Mint systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 13:11:00 Mint systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Nov 18 13:11:00 Mint systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has failed

**Comment by texasbobs** [comment]
I am having a hard time getting this running.  I'm on Mint instead of a rPi but I think I have most of it set up correctly.  My problem is with the configparser.  I can't seem to get it installed.  I've tried configparser and ConfigParser with python and python3.  Any help would be greatly appreciated.

bob@Mint:~/pi-hole-influx$ pip install ConfigParser
Collecting ConfigParser
  Using cached https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sNotAK/ConfigParser/



-- Unit piholeinflux.service has begun starting up.
Nov 18 13:11:00 Mint python[972]: Traceback (most recent call last):
Nov 18 13:11:00 Mint python[972]:   File "/home/bob/pi-hole-influx/piholeinflux.py", line 7, in <module>
Nov 18 13:11:00 Mint python[972]:     from configparser import configparser
Nov 18 13:11:00 Mint python[972]: ImportError: No module named configparser
Nov 18 13:11:00 Mint systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 13:11:00 Mint systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Nov 18 13:11:00 Mint systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has failed

**Comment by InfernoCV** [comment]
You shouldn't have to install each requirement manually.  The only you should tell it to install is with APT:  git and python-pip.

Then you clone the repo and tell pip to install based on the requirements.txt file that is cloned.
![image](https://user-images.githubusercontent.com/29135948/48729961-9fcc7f80-ebfe-11e8-89c9-7b00e38193ab.png)


If you use:

```python
pip install -r requirements.txt
```

that will install the correct versions of each requirement.  That's the beauty of pip with a requirements.txt file.

**Comment by texasbobs** [comment]
Going back was the key.  Thanks.  But I guess since this is on Mint and not Raspbian some things were different.
 I had to do the following:
pip install setuptools
pip install wheel
pip install -r requirements.txt

Now to try and get some data. :)
