### ISSUE TITLE
configparser requires Python '>=3.6' but the running Python is 3.5.3

### ISSUE THREAD

**Issue by vraicovi** [janw/pi-hole-influx#44]
So I'm attempting to install pi-hole influx the traditional way to my Pi-Hole running on a 3B+.  When I get up to the command 'pip3 install -r requirements.txt', it returns 'configparser requires Python '>=3.6' but the running Python is 3.5.3'.  I'm no Linux expert, but I'm no slouch either.  I managed to install 3.6.0 to the point where 'python --version' returns 'Python 3.6.0' now, but when I re-run the pip3 command, no dice - same error.

Any ideas on where to go?  I'm sure I'm just missing something simple...

**Comment by janw** [comment]
Hi @vraicovi. Sorry about this, the dependency to configparser was unused and I removed it in 1db1c05bd2d566598e96da3c97feeff6a2915b72. After updating to that version, you should be able to install the daemon on Python 3.5
