### ISSUE TITLE
Mapping for user.toml isn't correct

### ISSUE THREAD

**Issue by nomad64** [janw/pi-hole-influx#47]
I deployed this to a docker host and put all of my variables into a custom user.toml file. Per the instructions, I mapped this file to `/user.toml`. However, this didn't seem to be read by the service, as the logs always tried to connect to localhost instead of my configured Pihole instance. 

I was able to get it to work by mapping my custom toml to `/app/user.toml` and marking it as `RO`.

Am I mis-reading the documentation or missing something?

**Comment by janw** [comment]
Hey, You're right, that was a bug in the Dockerfile and parsing of the config. 

It's been fixed in [v2](https://github.com/janw/pi-hole-influx/pull/66), where the config now is expected under `/config/user.toml`.
