### ISSUE TITLE
cant run the python without errors

### ISSUE THREAD

**Issue by ikorbln** [janw/pi-hole-influx#52]
Hello,

I moved my tools to a new PC, so on my old one i have this up and running.
I cant get it to run on the new one, i allways end up with this error:

`Traceback (most recent call last):
  File "piholeinflux.py", line 18, in <module>
    settings.validators.validate()
  File "/usr/local/lib/python3.7/dist-packages/dynaconf/validator.py", line 286, in validate
    validator.validate(self.settings)
  File "/usr/local/lib/python3.7/dist-packages/dynaconf/validator.py", line 163, in validate
    self._validate_items(settings, settings.current_env)
  File "/usr/local/lib/python3.7/dist-packages/dynaconf/validator.py", line 177, in _validate_items
    self.messages["must_exist_true"].format(name=name, env=env)
dynaconf.validator.ValidationError: INSTANCES is required in env main`

I run the python by hand as root, i created my user.toml and there ist this instance defined:
`instances = "pihole=http://192.168.232.12/admin/api.php"`

So i cant see were the problem is.
btw, i installed alle the requirements.txt without errors.

**Comment by ikorbln** [comment]
I just compared the two pc´s. The working one has python 3.5 and the bad one has python 3.7

**Comment by FLIPNEUS** [comment]
I have the same issue. No matter how I configure the instances variable, it crashes with that error. Running Python 3.7.3 on an up-to-date version of Raspberry Pi OS on a Raspberry Pi Zero W.

**Comment by FLIPNEUS** [comment]
> I have the same issue. No matter how I configure the instances variable, it crashes with that error. Running Python 3.7.3 on an up-to-date version of Raspberry Pi OS on a Raspberry Pi Zero W.

Strike that. It's not a Python 3.7 issue. It is related to what looks like a [breaking change](https://www.dynaconf.com/release_notes/) in version 3.0.0 of the Dynaconf module. To resolve the issue, downgrade to the last version in the 2.x series:

`pip3 install --upgrade dynaconf==2.2.3`

This resolved the issue for me.

@ikorbln Can you confirm if this worked for you?

**Comment by ikorbln** [comment]
@FLIPNEUS yes, that helps. It works now. So as a workarround changing the requirements.txt to install not >=, it has to install only version 2.2.3
