### ISSUE TITLE
dynaconf.validator.ValidationError: INSTANCES is required in env main

### ISSUE THREAD

**Issue by Bboy486** [janw/pi-hole-influx#55]
**sudo journalctl --unit=piholeinflux** 

Aug 27 19:46:16 raspberrypi python3[553]: dynaconf.validator.ValidationError: INSTANCES is required in env main
Aug 27 19:46:16 raspberrypi systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Aug 27 19:46:16 raspberrypi systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Aug 27 19:46:16 raspberrypi systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
Aug 27 19:47:04 raspberrypi systemd[1]: piholeinflux.service: Service RestartSec=30s expired, scheduling restart.
Aug 27 19:47:04 raspberrypi systemd[1]: piholeinflux.service: Scheduled restart job, restart counter is at 1.
Aug 27 19:47:04 raspberrypi systemd[1]: Stopped Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.

**python3 piholeinflux.py**

 python3 piholeinflux.py
Traceback (most recent call last):
  File "piholeinflux.py", line 18, in <module>
    settings.validators.validate()
  File "/home/pi/.local/lib/python3.7/site-packages/dynaconf/validator.py", line 296, in validate
    validator.validate(self.settings)
  File "/home/pi/.local/lib/python3.7/site-packages/dynaconf/validator.py", line 166, in validate
    self._validate_items(settings, settings.current_env)
  File "/home/pi/.local/lib/python3.7/site-packages/dynaconf/validator.py", line 189, in _validate_items
    self.messages["must_exist_true"].format(name=name, env=env)
dynaconf.validator.ValidationError: INSTANCES is required in env main

**Comment by lmondoux** [comment]
I'm getting the same error. I had this running for months, moved to a new system, and now getting this error despite having instances declared in the conf file.

**Comment by lmondoux** [comment]
@janw - Any chance you could take a look at this error? Would love to get this running again.

**Comment by janw** [comment]
Sorry for being so unresponsive about this issue. #53 should have fixed this issue as well. Thanks again for reporting it.

**Comment by lmondoux** [comment]
Thanks so much! Everything is working again.
