### ISSUE TITLE
Unable to run armv7 tag in a Raspberry Pi 3

### ISSUE THREAD

**Issue by goliath888** [janw/pi-hole-influx#56]
I am trying to run with docker in a Raspberry Pi 3, with the tag :armv7, but I am getting this error message: 
> exec user process caused "exec format error"

I had this running before, but I had to rebuild my system and when trying to make it work now, it does not work. This message I think it is because the image is not the correct with the system, but it should work, because Pi 3 is arm. Also tried with no tag, but same error.

**Comment by schattenpinguin** [comment]
Same here on Raspberry Pi 3 running Raspbian (Debian Version 10.6) and docker-ce 19.03.13.

Image was working quite a long time, including autoupdate via watchtower.
But then data collection stopped unexpectedly weeks ago.

If i clone this repository and rebuild the image on my own, it´s running properly!

x86 versions is running properly on my PC (Virtual-Box with Debian VM running docker)

**Comment by janw** [comment]
Apologies, I messed up a recent change to the arm docker build. Fixed in #57, and verified on my Pi to be working again. Cheers!
