### ISSUE TITLE
AttributeError After PiHole Update

### ISSUE THREAD

**Issue by nomad64** [janw/pi-hole-influx#60]
Something seems to be broken with the latest PiHole update. I haven't modified the configuration for quite a while and the container started having issues after I upgraded to the latest version.

Error output:
```
INFO: [pihole.pihpp03] Initialized for pihpp03 (https://pihpp03.home.sharpienet.com/admin/api.php)
WARNING: [pihole.pihpp03] Disabled SSL verification for Pi-hole requests
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'pihpp03.home.sharpienet.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "./piholeinflux.py", line 141, in <module>
    main()
  File "./piholeinflux.py", line 129, in main
    daemon = Daemon(single_run)
  File "./piholeinflux.py", line 86, in __init__
    Pihole(name, url) for name, url in settings.INSTANCES.items()
  File "./piholeinflux.py", line 86, in <listcomp>
    Pihole(name, url) for name, url in settings.INSTANCES.items()
  File "./piholeinflux.py", line 41, in __init__
    keys = ", ".join(data.keys())
AttributeError: 'list' object has no attribute 'keys'
```

user.toml (blank fields are redacted):
```toml
influxdb_host = 
influxdb_port = "8086"
influxdb_database = "pihole"
influxdb_username = "influxdb_pihole"
influxdb_password = 

request_verify_ssl = "False"

instances={pihpp03='https://pihpp03.home.sharpienet.com/admin/api.php', pihpp04='https://pihpp04.home.sharpienet.com/admin/api.php'}
```

PiHole version information:
Pi-hole v5.14.2
FTL v5.20
Web Interface v5.18

**Comment by niemalsnever** [comment]
Hi,

with version 5.14.2 of Pi-Hole more API endpoints require authentication (see https://pi-hole.net/blog/2022/12/21/pi-hole-ftl-v5-20-and-web-v5-18-released/#page-content and https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/. This includes the `.../api.php?summary` endpoint, which apparently used to be the default endpoint if none was specified.

I had success in updating my `user.toml` to include `?summary&auth=<TOKEN>` after the current API URL specified so for your it should read like this:

```
...

instances={pihpp03='https://pihpp03.home.sharpienet.com/admin/api.php?summary&auth=<TOKEN>', pihpp04='https://pihpp04.home.sharpienet.com/admin/api.php?summary&auth=<TOKEN>'}
```
Obviously you need to replace `<TOKEN>` in the URL with the API token for the respective Pi-Hole instance. You can find this token in the Pi-Hole settings.

After updating `user.toml` you can restart the pihole-influx.service systemd unit and the exporter should work again.

**Comment by nomad64** [comment]
@niemalsnever 

I updated my `user.toml` per your instructions above and the the container is now running successfully. Although the API token is now in the docker logs which isn't ideal, but manageable.

Thanks for the help!
