### ISSUE TITLE
influx error 400 ads_percentage_today

### ISSUE THREAD

**Issue by blakkmaan** [janw/pi-hole-influx#9]
i followed the guide and it seems there are succesfull items in the influxdb, BUT the service always quits after startup. here is the status:

● piholeinflux.service - Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization
   Loaded: loaded (/home/hendrik/pi-hole-influx/piholeinflux.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-02-16 22:44:30 CET; 18s ago
     Docs: https://github.com/janw/pi-hole-influx
  Process: 5119 ExecStart=/usr/bin/python3 /home/hendrik/pi-hole-influx/piholeinflux.py (code=exited, status=1/FAILURE)
 Main PID: 5119 (code=exited, status=1/FAILURE)
   Status: "Failed, to report to InfluxDB: 400: {"error":"partial write: field type conflict: input field \"ads_percentage_today\" on measurement \"pihole\" is type integer, already exists as type float dropped=1"}"

**Comment by blakkmaan** [comment]
my secondary pihole has 0,0% ads blocked today. could this be a cause for this error?

**Comment by janw** [comment]
Hi @blakkmaan, thanks for your report. I will look into it; could you post the raw JSON output of both your Piholes API endpoint http://hostname/admin/api.php?

**Comment by blakkmaan** [comment]
sorry for late reply:
1st Pihole:

`
domains_being_blocked | 716715
-- | --
dns_queries_today | 8157
ads_blocked_today | 2085
ads_percentage_today | 25.560867
unique_domains | 1466
queries_forwarded | 3721
queries_cached | 2336
clients_ever_seen | 6
unique_clients | 6
dns_queries_all_types | 8157
reply_NODATA | 1037
reply_NXDOMAIN | 63
reply_CNAME | 1869
reply_IP | 4210
privacy_level | 0
status | "enabled"
gravity_last_updated |  
file_exists | true
absolute | 1551304889
relative |  
days | "0"
hours | "23"
minutes | "46"
`
2nd Pihole:
`
domains_being_blocked | 716715
-- | --
dns_queries_today | 213
ads_blocked_today | 0
ads_percentage_today | 0
unique_domains | 40
queries_forwarded | 78
queries_cached | 135
clients_ever_seen | 2
unique_clients | 2
dns_queries_all_types | 213
reply_NODATA | 27
reply_NXDOMAIN | 24
reply_CNAME | 63
reply_IP | 82
privacy_level | 0
status | "enabled"
gravity_last_updated |  
file_exists | true
absolute | 1551305155
relative |  
days | "0"
hours | "23"
minutes | "39"
`
